// Catálogo da loja. Para adicionar/editar produtos, mexa só aqui.
// Imagens são ilustrações fictícias — troque `image` pela foto real quando tiver.
window.FS_CATEGORIES = [
  { id: "iscas", name: "Iscas Artificiais", short: "Iscas", image: "assets/img/products/stick-spirit-90.svg", copy: "Superfície, meia-água e fundo" },
  { id: "varas", name: "Varas", short: "Varas", image: "assets/img/products/vara-spirit-carbon.svg", copy: "Carbono, leves e sensíveis" },
  { id: "molinetes", name: "Molinetes e Carretilhas", short: "Molinetes", image: "assets/img/products/molinete-spirit-3000.svg", copy: "Recolhimento macio e drag forte" },
  { id: "linhas", name: "Linhas", short: "Linhas", image: "assets/img/products/linha-multi-8x.svg", copy: "Multi, mono e fluorocarbono" },
  { id: "acessorios", name: "Acessórios", short: "Acessórios", image: "assets/img/products/caixa-organizadora.svg", copy: "Alicates, caixas, anzóis e mais" },
  { id: "kits", name: "Kits Prontos", short: "Kits", image: "assets/img/products/kit-tucunare.svg", copy: "Tudo junto, mais barato" },
];

window.FS_SPECIES = [
  { id: "tucunare", name: "Tucunaré", emoji: "🔥", copy: "Ataque explosivo na superfície" },
  { id: "robalo", name: "Robalo", emoji: "🌊", copy: "Mangue, costeira e estuário" },
  { id: "traira", name: "Traíra", emoji: "🌿", copy: "Pesca no mato e na vegetação" },
  { id: "dourado", name: "Dourado", emoji: "⚡", copy: "Força bruta em água corrente" },
  { id: "tilapia", name: "Pesqueiro", emoji: "🎣", copy: "Tilápia, tambaqui e cia." },
];

window.FS_PRODUCTS = [
  {
    id: "stick-spirit-90", name: "Isca Stick Spirit 90", category: "iscas",
    price: 39.9, oldPrice: 49.9, rating: 4.9, reviews: 318, badge: "Mais vendida",
    species: ["tucunare", "robalo"],
    image: "assets/img/products/stick-spirit-90.svg",
    colors: ["#1a6dff", "#0b1530", "#f5c518"],
    short: "Meia-água, nado rebolado que o peixe não resiste.",
    description: "A queridinha da casa. A Stick Spirit 90 trabalha em meia-água com um nado rebolado e brilho que chama atenção de longe. Garateias reforçadas pra não abrir na briga.",
    specs: { Tamanho: "9 cm", Peso: "11 g", Ação: "Meia-água (0,5 a 1 m)", Garateias: "2x #4 reforçadas" },
  },
  {
    id: "zara-walk-110", name: "Zara Walk 110", category: "iscas",
    price: 44.9, rating: 4.8, reviews: 204, badge: "Superfície",
    species: ["tucunare", "robalo", "traira"],
    image: "assets/img/products/zara-walk-110.svg",
    colors: ["#1a6dff", "#ffffff", "#d81e3a"],
    short: "Zigue-zague na superfície pra provocar ataque.",
    description: "Isca de superfície clássica pro 'walk the dog'. Toques curtos de ponta de vara e ela anda de um lado pro outro, fazendo barulho e provocando ataques de cinema.",
    specs: { Tamanho: "11 cm", Peso: "16 g", Ação: "Superfície", Garateias: "2x #2" },
  },
  {
    id: "popper-explosao-70", name: "Popper Explosão 70", category: "iscas",
    price: 34.9, rating: 4.7, reviews: 156,
    species: ["tucunare", "traira", "robalo"],
    image: "assets/img/products/popper-explosao-70.svg",
    colors: ["#1a6dff", "#f5c518"],
    short: "Boca côncava que espirra água e faz barulho.",
    description: "Cada puxada faz um 'bloop' que acorda qualquer predador. Perfeita pro amanhecer e fim de tarde, quando o peixe está caçando na superfície.",
    specs: { Tamanho: "7 cm", Peso: "12 g", Ação: "Superfície", Garateias: "2x #4" },
  },
  {
    id: "minnow-ghost-110", name: "Minnow Ghost 110", category: "iscas",
    price: 46.9, rating: 4.8, reviews: 97, badge: "Novidade",
    species: ["robalo", "dourado"],
    image: "assets/img/products/minnow-ghost-110.svg",
    colors: ["#cbd5e1", "#4b5563"],
    short: "Cor natural pra água clara e peixe desconfiado.",
    description: "Acabamento 'ghost' que imita o lambari. Ideal pra água clara e peixe desconfiado. Barbela média, trabalha até 1,2 m de profundidade.",
    specs: { Tamanho: "11 cm", Peso: "14 g", Ação: "Meia-água (até 1,2 m)", Garateias: "2x #4" },
  },
  {
    id: "crank-deep-60", name: "Crankbait Deep 60", category: "iscas",
    price: 42.9, rating: 4.6, reviews: 88,
    species: ["tucunare", "dourado"],
    image: "assets/img/products/crank-deep-60.svg",
    colors: ["#166534", "#f5c518"],
    short: "Barbela longa pra buscar o peixe no fundo.",
    description: "Quando o peixe tá lá embaixo, ela vai buscar. Barbela longa, mergulha rápido e vibra forte. Ótima pra pesca em pedra e galhada.",
    specs: { Tamanho: "6 cm", Peso: "13 g", Ação: "Fundo (2 a 3 m)", Garateias: "2x #4" },
  },
  {
    id: "shad-soft-4", name: "Shad Soft 4\" + Jig Head", category: "iscas",
    price: 29.9, rating: 4.7, reviews: 241,
    species: ["robalo", "traira", "tilapia"],
    image: "assets/img/products/shad-soft-4.svg",
    colors: ["#7dd3fc", "#ffffff", "#3fae5a"],
    short: "Pacote com 5 shads + 3 jig heads.",
    description: "A isca soft mais versátil que existe. Rabo de pá que vibra até no recolhimento lento. Vem com 5 shads e 3 jig heads de 7 g.",
    specs: { Conteúdo: "5 shads + 3 jig heads", Tamanho: "10 cm", "Jig head": "7 g, anzol 2/0", Ação: "Meia-água e fundo" },
  },
  {
    id: "colher-prata-15g", name: "Colher Prata 15 g", category: "iscas",
    price: 19.9, rating: 4.5, reviews: 132,
    species: ["dourado", "robalo"],
    image: "assets/img/products/colher-prata-15g.svg",
    colors: ["#c7d0dd", "#e5c07b"],
    short: "Simples, barata e pega peixe em todo lugar.",
    description: "Aquela isca que todo pescador tem na caixa. Gira, brilha e arremessa longe. Funciona em rio, represa e mar.",
    specs: { Peso: "15 g", Material: "Metal cromado", Ação: "Meia-água", Garateia: "1x #2" },
  },
  {
    id: "jig-skirt-10g", name: "Jig de Saia 10 g", category: "iscas",
    price: 27.9, rating: 4.6, reviews: 64,
    species: ["tucunare", "dourado"],
    image: "assets/img/products/jig-skirt-10g.svg",
    colors: ["#1a6dff", "#f5c518"],
    short: "Saia de silicone com movimento na queda.",
    description: "Jig com saia de silicone que se abre na queda e no toque de vara. Excelente pra pesca vertical e em estrutura.",
    specs: { Peso: "10 g", Anzol: "3/0 black nickel", Saia: "Silicone 40 fios", Ação: "Fundo" },
  },
  {
    id: "sapinho-soft-frog", name: "Sapinho Soft Frog", category: "iscas",
    price: 36.9, rating: 4.8, reviews: 177, badge: "Anti-enrosco",
    species: ["traira"],
    image: "assets/img/products/sapinho-soft-frog.svg",
    colors: ["#3fae5a", "#f5c518", "#0b1530"],
    short: "Passa pela vegetação sem enroscar.",
    description: "O terror da traíra. Corpo macio e anzol duplo protegido: você joga em cima do aguapé e ele passa sem enroscar.",
    specs: { Tamanho: "6 cm", Peso: "14 g", Ação: "Superfície", Anzol: "Duplo 4/0 anti-enrosco" },
  },
  {
    id: "vara-spirit-carbon", name: "Vara Spirit Carbon 6'0\"", category: "varas",
    price: 389.9, oldPrice: 449.9, rating: 4.9, reviews: 142, badge: "Top de linha",
    species: ["tucunare", "robalo", "traira"],
    image: "assets/img/products/vara-spirit-carbon.svg",
    colors: ["#0b1530", "#1a6dff"],
    short: "Carbono IM8, leve e sensível. Pra carretilha.",
    description: "Blank em carbono IM8: leve na mão e sensível pra sentir cada toque. Ação rápida, ideal pra trabalhar iscas artificiais o dia inteiro sem cansar.",
    specs: { Comprimento: "1,83 m (6'0\")", Libragem: "10 a 20 lb", Ação: "Rápida", Partes: "Inteiriça", Material: "Carbono IM8" },
  },
  {
    id: "vara-telescopica", name: "Vara Telescópica Viagem 2,10 m", category: "varas",
    price: 159.9, rating: 4.4, reviews: 76,
    species: ["tilapia", "robalo"],
    image: "assets/img/products/vara-telescopica.svg",
    colors: ["#1d1f24", "#3d8bff"],
    short: "Fecha com 50 cm. Cabe no porta-malas.",
    description: "Pra quem não perde uma chance de pescar. Fecha com 50 cm, abre em segundos e aguenta peixe bom. Pra molinete.",
    specs: { Comprimento: "2,10 m", Fechada: "50 cm", Libragem: "8 a 17 lb", Material: "Fibra + carbono" },
  },
  {
    id: "molinete-spirit-3000", name: "Molinete Spirit 3000", category: "molinetes",
    price: 289.9, oldPrice: 329.9, rating: 4.8, reviews: 189,
    species: ["robalo", "tilapia", "dourado"],
    image: "assets/img/products/molinete-spirit-3000.svg",
    colors: ["#0b1530", "#1a6dff"],
    short: "6 rolamentos, drag de 8 kg. Macio e forte.",
    description: "Recolhimento macio com 6 rolamentos e drag de 8 kg pra segurar peixe brigador. Carretel de alumínio que já aceita multifilamento.",
    specs: { Tamanho: "3000", Rolamentos: "6", Drag: "8 kg", Relação: "5.2:1", Capacidade: "0,30 mm / 150 m" },
  },
  {
    id: "carretilha-storm-lp", name: "Carretilha Storm Low Profile", category: "molinetes",
    price: 459.9, rating: 4.9, reviews: 121, badge: "Mais vendida",
    species: ["tucunare", "traira", "robalo"],
    image: "assets/img/products/carretilha-storm-lp.svg",
    colors: ["#0b1530", "#1a6dff"],
    short: "Perfil baixo, 7.2:1 e freio magnético.",
    description: "Leve, compacta e rápida. Relação 7.2:1 pra trabalhar iscas de superfície e freio magnético que acaba com a cabeleira.",
    specs: { Relação: "7.2:1", Rolamentos: "10", Drag: "6 kg", Freio: "Magnético", Manivela: "Direita ou esquerda" },
  },
  {
    id: "linha-multi-8x", name: "Linha Multifilamento 8X 150 m", category: "linhas",
    price: 119.9, rating: 4.8, reviews: 263,
    species: ["tucunare", "robalo", "traira", "dourado"],
    image: "assets/img/products/linha-multi-8x.svg",
    colors: ["#1a6dff", "#3fae5a", "#f5c518"],
    short: "8 fios trançados. Fina, forte e arremessa longe.",
    description: "Trançado de 8 fios: mais lisa, mais redonda e arremessa mais longe. Não estica, então você sente cada toque.",
    specs: { Fios: "8", Diâmetro: "0,23 mm", Resistência: "30 lb", Comprimento: "150 m" },
  },
  {
    id: "linha-fluoro-leader", name: "Leader Fluorocarbono 50 m", category: "linhas",
    price: 69.9, rating: 4.7, reviews: 98,
    species: ["robalo", "tucunare"],
    image: "assets/img/products/linha-fluoro-leader.svg",
    colors: ["#9fd8ff"],
    short: "Invisível na água e resistente à abrasão.",
    description: "Praticamente invisível na água e aguenta raspão em pedra e galhada. O leader que faz diferença com peixe esperto.",
    specs: { Diâmetro: "0,40 mm", Resistência: "25 lb", Comprimento: "50 m", Material: "100% fluorocarbono" },
  },
  {
    id: "alicate-contencao", name: "Alicate de Bico Inox", category: "acessorios",
    price: 79.9, rating: 4.7, reviews: 84,
    species: [],
    image: "assets/img/products/alicate-contencao.svg",
    colors: ["#1a6dff", "#0b1530"],
    short: "Tira anzol, corta linha e abre argola.",
    description: "Aço inox que não enferruja, corta multifilamento e tem ponta fina pra abrir argola. Vem com coldre e cordão espiral.",
    specs: { Material: "Aço inox", Tamanho: "18 cm", Inclui: "Coldre + cordão" },
  },
  {
    id: "caixa-organizadora", name: "Caixa Organizadora Spirit", category: "acessorios",
    price: 99.9, rating: 4.6, reviews: 112,
    species: [],
    image: "assets/img/products/caixa-organizadora.svg",
    colors: ["#1a6dff"],
    short: "2 bandejas, divisórias removíveis.",
    description: "Sua caixa de iscas organizada de verdade. Divisórias removíveis, trava reforçada e plástico que aguenta sol e chuva.",
    specs: { Bandejas: "2", Divisórias: "Até 24", Tamanho: "36 x 22 x 18 cm" },
  },
  {
    id: "anzol-wide-gap", name: "Anzol Wide Gap (50 un.)", category: "acessorios",
    price: 24.9, rating: 4.5, reviews: 59,
    species: ["traira", "tilapia", "robalo"],
    image: "assets/img/products/anzol-wide-gap.svg",
    colors: ["#3b4656"],
    short: "Abertura larga, fisgada certeira.",
    description: "Anzol de abertura larga, perfeito pra iscas soft. Ponta química afiada que fisga com pouca força.",
    specs: { Quantidade: "50 unidades", Tamanhos: "1/0, 2/0 e 3/0", Acabamento: "Black nickel" },
  },
  {
    id: "bone-fishing-spirit", name: "Boné Fishing Spirit", category: "acessorios",
    price: 69.9, rating: 4.9, reviews: 45, badge: "Da casa",
    species: [],
    image: "assets/img/products/bone-fishing-spirit.svg",
    colors: ["#0b1530", "#1a6dff"],
    short: "Proteção pro sol e estilo no barco.",
    description: "Boné oficial Fishing Spirit. Aba curva, regulagem traseira e tecido que seca rápido. Pra mostrar de que lado do rio você tá.",
    specs: { Tamanho: "Único (regulável)", Tecido: "Dry-fit", Aba: "Curva" },
  },
  {
    id: "kit-tucunare", name: "Kit Caçada ao Tucunaré", category: "kits",
    price: 119.9, oldPrice: 149.7, rating: 4.9, reviews: 73, badge: "Economize 20%",
    species: ["tucunare"],
    image: "assets/img/products/kit-tucunare.svg",
    colors: ["#1a6dff", "#f5c518", "#f97316"],
    short: "3 iscas certeiras + leader. Só ir pra água.",
    description: "Montamos o kit que a gente leva: Stick Spirit 90, Zara Walk 110 e Popper Explosão 70, mais 10 m de leader fluorocarbono. Só chegar e pescar.",
    specs: { Inclui: "Stick 90 + Zara 110 + Popper 70 + leader 10 m", Economia: "R$ 29,80" },
  },
];
